baseURL = 'https://gerasolodov.github.io/hw3/'
languageCode = 'ru-ru'
title = '–î–Ω–µ–≤–Ω–∏–∫ –î–∂–æ–Ω–Ω–∏ –°–∫–æ–ª–∏–æ–∑–∞'
theme = 'congo'

[pagination]
  pagerSize = 5

[params]
  description = '–•—Ä–æ–Ω–∏–∫–∏ –æ—Ö–æ—Ç–Ω–∏–∫–∞ –∑–∞ –≥–æ–ª–æ–≤–∞–º–∏ –Ω–∞ —Ç–≤–∞—Ä–µ–π –∏–∑ –∏–Ω—ã—Ö –º–∏—Ä–æ–≤. –ì–≤–æ–∑–¥–∏, —Å–≤–∏–Ω–µ—Ü, –¥—Ä–µ–≤–Ω–∏–µ –∑–∞–∫–ª–∏–Ω–∞–Ω–∏—è.'
  defaultAppearance = 'dark'
  showReadingTime = true
  showWordCount = true
  showPostNavLinks = true
  
  [params.author]
    name = "–î–∂–æ–Ω–Ω–∏ '–ü–æ–∑–≤–æ–Ω–æ—á–Ω–∏–∫' –°–∫–æ–ª–∏–æ–∑"
    image = "/img/avatar.jpg"
    bio = "–û—Ö–æ—Ç–Ω–∏–∫ –Ω–∞ –º–æ–Ω—Å—Ç—Ä–æ–≤ –≤ –∑–µ–º–ª—è—Ö –º–µ–∂–¥—É –º–∏—Ä–∞–º–∏"
    reward = "500 –∑–æ–ª–æ—Ç—ã—Ö –∑–∞ –≥–æ–ª–æ–≤—É"
    location = "–ö–∞–Ω—å–æ–Ω –ë–µ–∑–¥–Ω—ã"
    weapon = "–î–≤—É—Å—Ç–≤–æ–ª–∫–∞ '–ì–æ–≤–æ—Ä–∏—Ç–µ–ª—å'"

[menu]
  [[menu.main]]
    name = 'üèúÔ∏è –õ–∞–≥–µ—Ä—å'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'üìú –û—Ö–æ—Ç–Ω–∏—á—å–∏ –∑–∞–º–µ—Ç–∫–∏'
    url = '/posts/'
    weight = 2
  [[menu.main]]
    name = '‚öîÔ∏è –î–æ—Å–∫–∞ –∑–∞–∫–∞–∑–æ–≤'
    url = '/bounties/'
    weight = 3

[params.assets]
  disableFingerprinting = true